export { default as AddElementTab } from './AddElement'
export { default as AddSectionTab } from './AddSection'
export { default as InfoTab } from './Info'
export { default as PagesTab } from './Pages'
export { default as SiteSettingsTab } from './SiteSettings'